arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD/"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/v1.10/alpine/"
    - REPO="quay.io/ibmz/fluentd"
    - TAG="$REPO:1.10"
before_script: 
  - cd $BUILD_DIR && chmod +x *
  - cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT_USER -p $ROBOTTOKEN
script: 
  - docker build $BUILD_DIR --tag $TAG
  - cd $TEST_DIR && bash $TEST_SCRIPT 
after_script:
  - docker push $TAG
